# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nanala/v1/nanala.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


class VectorBackbone(betterproto.Enum):
    VECTOR_BACKBONE_UNSPECIFIED = 0
    VECTOR_BACKBONE_POPENV3 = 1


@dataclass
class SynthesizeRequest(betterproto.Message):
    sequence: str = betterproto.string_field(1)
    backbone: "VectorBackbone" = betterproto.enum_field(2)


@dataclass
class SynthesizeResponse(betterproto.Message):
    full_sequence: str = betterproto.string_field(1)


class NanalaServiceStub(betterproto.ServiceStub):
    """
    In the future, direct communication with Nanala servers will be possible.
    For now, this is an empty service.
    """

    async def synthesize(
        self, *, sequence: str = "", backbone: "VectorBackbone" = 0
    ) -> SynthesizeResponse:
        request = SynthesizeRequest()
        request.sequence = sequence
        request.backbone = backbone

        return await self._unary_unary(
            "/nanala.v1.NanalaService/Synthesize",
            request,
            SynthesizeResponse,
        )
